name: Train and Predict Workflow

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [predict_request]

jobs:
  train:
    if: github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Train LSTM Model
        run: |
          python train.py

      - name: Commit and Push Model File
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Configurar git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Establecer la URL remota con el token
          git remote set-url origin https://$PAT_TOKEN@github.com/${{ github.repository }}.git
      
          # Añadir los cambios y hacer commit
          git add model.h5
          git commit -m "Add/Update trained model file (model.h5)"
          
          # Hacer push al repositorio
          git push origin main


  predict:
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Predictions
        env:
          PREDICTION_INPUT: ${{ github.event.client_payload.datos }}
        run: |
          python predict.py "${{ env.PREDICTION_INPUT }}"

      - name: Finalize Predictions
        run: |
          echo "Prediction workflow completed successfully."
