name: Predict Workflow

on:
  workflow_dispatch:
    inputs:
      datos:
        description: 'Datos para la predicción'
        required: true

jobs:
  predict:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Predictions
        env:
          PREDICTION_INPUT: ${{ github.event.inputs.datos }}
        run: |
          echo "${{ env.PREDICTION_INPUT }}"
          python predict.py "${{ env.PREDICTION_INPUT }}"
      
      - name: Upload Prediction Artifact
        uses: actions/upload-artifact@v3
        with:
          name: prediction-result
          path: predicho.txt

      - name: Finalize Predictions
        run: |
          echo "Prediction workflow completed successfully."
